# Generated by Django 4.1.4 on 2023-02-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expensecategory_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['-created_at']},
        ),
    ]
