# Generated by Django 4.1.4 on 2023-02-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
