# Generated by Django 4.1.4 on 2023-02-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ['-created_at']},
        ),
    ]
